apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mapMeGcp
  annotations:
    version: v0.0.1
    # Change description to something which suits your application
    description: "description"
    # Change authors to yourself to begin with
    authors: "authors"
spec:
  components:
    - name: mapMeGcp
      type: component
      properties:
        # replace with image on gh 
        image: file://./build/mapMeGcp_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        # Link component with nats-core to get publishing capability
        - type: link
          properties:
            target:
              name: nats-core
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
        - type: link
          properties:
            target: map-nats-kv
            namespace: mattilsynet
            package: map-kv
            interfaces: [key-value]
            target_config:
              - name: nats-kv
                properties:
                  bucket: "map-me-gcp"
                  url: "nats://localhost:4222"
        - type: link
          properties:
            target:
              name: map-me-gcp-cloudrunjob-provider
              config:
                - name: map-me-gcp-cloudrunjob-provider-config
                  properties:
                    project_id: "map-ops-dev-c2c8"
                    image: "us-docker.pkg.dev/cloudrun/container/job:latest"
                    location: "europe-north1"
                    # map-me-gcp-cloudrunjob-sa: |
              secrets:
                - name: map-me-gcp-cloudrunjob-sa
                  properties:
                    policy: nats-kv
                    key: map-me-gcp-cloudrunjob-sa
            namespace: mattilsynet
            package: me-gcp-cloudrun-job-admin
            interfaces: [me-gcp-cloudrun-job-admin]

    # Setup nats-core provider, such that it's deployed to the wadm server and made available for this application for linking
    #
    - name: nats-core
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
        config:
          - name: nats-core-config
            properties:
              cluster_uris: "nats://127.0.0.1:4222"
      traits:
        - type: spreadscalar
          properties:
            replicas: 1

    # Nats KV provider, look in component target for configuration example, OBS! watch-key not implemented as of 12.02.2025
    - name: map-nats-kv
      type: capability
      properties:
        image: ghcr.io/Mattilsynet/map-nats-kv:v0.0.2-pre-25
      #Link the component to nats-kv to watch-all on a given bucket
      traits:
        - type: link
          properties:
            target: mapMeGcp
            namespace: mattilsynet
            package: map-kv
            interfaces: [key-value-watcher]
            source_config:
              - name: nats-kv-watcher-config
                properties:
                  bucket: "map-me-gcp"
                  url: "nats://localhost:4222"
                  startup_time: "5"
    - name: map-me-gcp-cloudrunjob-provider
      type: capability
      properties:
        image: ghcr.io/Mattilsynet/map-me-gcp-cloudrunjob:v0.0.2.3
      traits:
        - type: spreadscaler
          properties:
 
